### ISSUE TITLE
Just first letter in steps on json

### ISSUE THREAD

**Issue by robsonpolicarpo** [wswebcreation/wdio-cucumberjs-json-reporter#11]
**Environment (please complete the following information):**
 - **Node.js version:** [e.g. 8.9.1]
 - **NPM version:** [e.g. 5.8.0]
 - **webdriver.io version:** [e.g. 5.11.0]
 - **@wdio/cucumber-framework version:** [e.g. 5.11.0]
 - **wdio-cucumberjs-json-reporter version:** [e.g. 1.0.8]

**Config of webdriver.io and the reporter**

```js
reporters: [
        'spec',
        'cucumberjs-json',
    ],

onComplete: () => {
        generate({
            jsonDir: '.tmp/json/',
            reportPath: '.tmp/report/',
            // for more options see https://github.com/wswebcreation/multiple-cucumber-html-reporter#options
        });
    },

```

**Describe the bug**
name of step just save the first letter.

```json
{
"steps":[  
               {  
                  "arguments":[  

                  ],
                  "keyword":"",
                  "name":"\"",
                  "result":{  
                     "status":"passed",
                     "duration":4146000000
                  },
                  "line":"",
                  "match":{  
                     "location":"can not be determined with webdriver.io"
                  }
               },
]
}
```

![image](https://user-images.githubusercontent.com/16124034/63511213-f4b36400-c4b6-11e9-9ec6-50cd0c317717.png)

**To Reproduce**
I have no idea why it's happening. I tried change the versions of the "wdio-cucumberjs-json-reporter" but doesn't work.

**Additional context**

**Updated with proper markdown**

**Comment by yuripg1** [comment]
I'm experiencing the same problem.

Are you using a language other than English? I'm using Portuguese.

Taking a look at the code, it looks like the library matches against English keywords only:
https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L288

**Comment by wswebcreation** [comment]
Hi @robsonpolicarpo and @yuripg1 

Hmm, that's right, both this module as the reporter are based on English. If you only use the proper `Given|When|Then|And` it should work.

I'll add it to the FAQ in the readme.

Going to close it because I only support English with both my modules. It might be a feature request, but then I need to support a lot of languages which will be harder

**Comment by robsonpolicarpo** [comment]
> I'm experiencing the same problem.
> 
> Are you using a language other than English? I'm using Portuguese.
> 
> Taking a look at the code, it looks like the library matches against English keywords only:
> https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L288
> 
> Edit: Changing my feature files to english fixed the problem, so I believe it's related to the language used.

Yes! It work for me when I change the steps in feature to English. I was using in Portuguese too. Thank you!

**Comment by wswebcreation** [comment]
@robsonpolicarpo 

Thanks to @yuripg1 this module now supports multiple languages, see this release https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.1.0

**Comment by robsonpolicarpo** [comment]
> @robsonpolicarpo
> 
> Thanks to @yuripg1 this module now supports multiple languages, see this release https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.1.0

@wswebcreation thanks for mention me! It's very useful for me!

@yuripg1 Valeu mano! Agora minhas features podem voltar a ter uma linguagem só.
