### ISSUE TITLE
TypeError: keyword.trimEnd is not a function

### ISSUE THREAD

**Issue by tamil777selvan** [wswebcreation/wdio-cucumberjs-json-reporter#14]
**Environment**
 - **Node.js version:**  8.9
 - **NPM version:** 6.11.2
 - **webdriver.io version:** 5.12.5
 - **@wdio/cucumber-framework version:** 5.12.3
 - **wdio-cucumberjs-json-reporter version:** 1.1.0

**Config of webdriver.io and the reporter**
config.afterScenario = function (uri, feature, scenario, result, sourceLocation) {
        if (result.status === 'failed') {
            const screenShot = global.browser.takeScreenshot();
            return cucumberJson.attach(screenShot, 'image/png');
        }
    };

**Describe the bug**
With the latest version of "wdio-cucumberjs-json-reporter" unable to run test. As soon as the config is loaded getting "TypeError: keyword.trimEnd is not a function" error.

**To Reproduce**
Execute any cucumber test with above environment in wdio framework.

**Expected behavior**
Test should start with generating json reports.

**Snapshot**
![error](https://user-images.githubusercontent.com/49207189/64350262-4ba95500-cff0-11e9-864d-d79eb5f37f49.png)

**Comment by siva1711** [comment]
Hi, I am also facing the same issue with latest version of wdio-cucumberjs-json-reporter, If I remove this report from reporters in config file, tests are working fine. Thanks

**Comment by wswebcreation** [comment]
Hi @tamil777selvan and @siva1711 

I've released a fix, can you please check it and if fixed close the issue?

Thanks

**Comment by tamil777selvan** [comment]
Thanks for the fix @wswebcreation.

**Comment by wswebcreation** [comment]
You're welcome. It was my bad, I thought that Babel would transpile the `trimEnd()` but it didn't. Please also consider upgrading your node instance to 10 beause of the end of life support of 8 at the end of the year
