### ISSUE TITLE
Meta Data not getting Displayed

### ISSUE THREAD

**Issue by tamil777selvan** [wswebcreation/wdio-cucumberjs-json-reporter#16]
**Environment (please complete the following information):**
 - **Node.js version:** 10
 - **webdriver.io version:** 5.16.4
 - **@wdio/cucumber-framework version:** 5.16.4
 - **wdio-cucumberjs-json-reporter version:** 1.1.1

**Config of webdriver.io and the reporter**

```js
exports.config = {
  //..
reporters: ['spec', ['cucumberjs-json', {jsonFolder: 'tests/wdio/report/json/'}]];
capabilities: [{
            browserName: argv.browser,
            'cjson:metadata': {
                browser: {
                    name: argv.browser,
                    version: '58',
                },
                device: deviceName,
                platform: {
                    name: deviceType,
                    version: os.release()
                }
            }
        }],
..//
};
```

**Describe the bug**
Metadata not getting added to json report.

**To Reproduce**
Run any test with provided env.

**Expected behavior**
Metadata to be displayed in Report

**Snapshots**
![image](https://user-images.githubusercontent.com/49207189/68522651-98046000-02d3-11ea-8948-181fb5803335.png)

**Comment by wswebcreation** [comment]
Thanks for filling an issue, this has to do with the fact that there is a _breaking_ change in the order the hooks are now started in WebdriverIO's `WDIOReporter`.

They used to start like this

```log
[0-0] RUNNING in chrome - /__tests__/features/passed.feature
[0-0] onRunnerStart
[0-0] onSuiteStart
[0-0] onSuiteStart
[0-0] onSuiteStart
[0-0] PASSED in chrome - /__tests__/features/passed.feature
```

They now start like this

```log
[0-0] onSuiteStart
[0-0] RUNNING in chrome - /__tests__/features/passed.feature
[0-0] onRunnerStart
[0-0] onSuiteStart
[0-0] onSuiteStart
[0-0] PASSED in chrome - /__tests__/features/passed.feature
```

I need to figure this one out and come with a fix

**Comment by wswebcreation** [comment]
I've released version https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.1.2 which should fix this. Can you please try again and if it works for you close the issue?

**Comment by mgrybyk** [comment]
hey guys, actually it's a defect in wdio, raised a PR with fix

**Comment by tamil777selvan** [comment]
@wswebcreation, Working with the fix which you have provided. Yet will try with the fix which @mgrybyk mentioned for wdio.

**Comment by tamil777selvan** [comment]
@wswebcreation and @mgrybyk, now the meta data is getting populated with latest webdriver version. Environment used with below mentioned version works as expected.

* **Node.js version:** 10
* **webdriver.io version:** 5.16.6
* **@wdio/cucumber-framework version:** 5.16.6
* **wdio-cucumberjs-json-reporter version:** 1.1.1

**Comment by wswebcreation** [comment]
Awesome, going to close it now
