### ISSUE TITLE
Breaks in WDIO 6: Cannot read property 'cjson:metadata' of undefined

### ISSUE THREAD

**Issue by bkrrrr** [wswebcreation/wdio-cucumberjs-json-reporter#23]
Our Project can't run after upgrading to WDIO 6.
It looks like the API has changed a bit.

**Error** 
[0-0] 2020-03-31T11:35:52.667Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'cjson:metadata' of undefined

Fast investigation with console.log
![image](https://user-images.githubusercontent.com/14314310/78022476-47aa9f00-7355-11ea-8257-c746ee63cde6.png)

Package.json
```"@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/register": "^7.9.0",
    "@ui5/cli": "^1.14.0",
    "@wdio/cli": "^6.0.8",
    "@wdio/cucumber-framework": "^6.0.8",
    "@wdio/junit-reporter": "^6.0.8",
    "@wdio/local-runner": "^6.0.8",
    "@wdio/selenium-standalone-service": "^6.0.8",
    "@wdio/spec-reporter": "^6.0.8",
    "@wdio/sync": "^6.0.8",
    "chai": "^4.2.0",
    "deepmerge": "^4.2.2",
    "eslint": "^6.8.0",
    "eslint-plugin-jsdoc": "^22.1.0",
    "npm-run-all": "^4.1.5",
    "nyc": "^15.0.0",
    "rimraf": "^3.0.2",
    "wdio-cucumberjs-json-reporter": "^1.1.3"
```

**Comment by wswebcreation** [comment]
Hi @bkrrrr 

This is a _breaking change_ in WebdriverIO. In V5 it provided the custom meta data you could provide on the capabilities, in V6 they removed it. I'm now checking with the team how we can retrieve them. I'll keep you posted

**Comment by wswebcreation** [comment]
Hi @bkrrrr 

I've released a new version https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.2.0 which holds a temporary fix for this issue. I'm working with the team on a better fix

**Comment by guptapranay** [comment]
I also faced the same issue two days back. Did post question  on gitter. Thanks for this post. It will help me too to resolve the issue.

@wswebcreation thanks for the updates.

**Comment by guptapranay** [comment]
@wswebcreation Just ran test with temporary fix. I am not able to see Device details and OS version in HTML report. Is this because of temporary fix?
![Capture](https://user-images.githubusercontent.com/16861336/78469751-84094100-7741-11ea-80fc-1d4f6f8b5a01.PNG)

**Comment by wswebcreation** [comment]
@guptapranay 

Yep, see the meta data header in the readme

**Comment by seanuleh** [comment]
Any updates to getting this to work on WDIO v6? I may have some time during this week to assist, if you have a solution in mind and just need some assistance writing it up.

**Comment by wswebcreation** [comment]
@seanuleh @guptapranay @bkrrrr 

I've released a new version, this one should work properly with V6 and the extra meta data, see https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v2.0.0
