### ISSUE TITLE
Cucumber Reports Jenkins plugin compatibility

### ISSUE THREAD

**Issue by aklimkovich** [wswebcreation/wdio-cucumberjs-json-reporter#26]
Hello @wswebcreation ,
We are using Cucumber Reports Jenkins plugin https://plugins.jenkins.io/cucumber-reports/ for displaying test results and seems it can't parse - "elements": [   {   "keyword": "Scenario" - well and display 0%.
If add "type": "Scenario" it displays correct info about pass\fail scenarios. 

Is it possible to add new extra property "type": 'scenario' to the JSON report?

**Environment**
 - **Node.js version:** [v10.16.1]
 - **NPM version:** [6.4.1]
 - **webdriver.io version:** [6.0.14]
 - **@wdio/cucumber-framework version:** [6.0.14]
 - **wdio-cucumberjs-json-reporter version:** [1.2.0]

**Comment by bkrrrr** [comment]
we face also a problem with the jenkins plugin:
https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/52c9b2e94442509ebcb39072664d6c43e2613ef7/lib/reporter.js#L200

the dateTime in the filename is causing some trouble. a flag to switch this off would also be very helpful. Jenkins is matching old/new results via filename.

**Comment by wswebcreation** [comment]
@aklimkovich 

Thanks, I'll check if I can get this info in a detailed way with WebdriverIO, see https://relishapp.com/cucumber/cucumber/docs/formatters/json-output-formatter for the out put

**Comment by wswebcreation** [comment]
@bkrrrr 

> we face also a problem with the jenkins plugin:
> https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/52c9b2e94442509ebcb39072664d6c43e2613ef7/lib/reporter.js#L200
> 
> the dateTime in the filename is causing some trouble. a flag to switch this off would also be very helpful. Jenkins is matching old/new results via filename.

Thanks, can you  file a separate ticket for it? It's a different issue. Secondly, if you run 1 feature file on multiple browsers, how should the file be named because you will get multiple files with the same name meaning it will overwrite it constantly

**Comment by wswebcreation** [comment]
@aklimkovich 

I can't determine the type of Scenario (background, normal or outline) so I've added the normal type. I've made a fix, see https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.2.1

Can you please test it and see if it works, if so, please close this issue?

**Comment by wswebcreation** [comment]
@bkrrrr 

I think I fixed the problem with the multiple outputs and released version 1.3, can you check that one here https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v1.3.0

**Comment by aklimkovich** [comment]
@bkrrrr , Thank you, your solution works well! I expected you just add type: SCENARIO , but anyway works perfect now !

**Comment by wswebcreation** [comment]
@aklimkovich 

I think you meant me 😉

**Comment by aklimkovich** [comment]
@wswebcreation , my apologies, of course i meant you :)
