### ISSUE TITLE
json file is not generating when trying to create separate instance for browser

### ISSUE THREAD

**Issue by krishna01012002** [wswebcreation/wdio-cucumberjs-json-reporter#29]
**Describe your question with as much detail as possible**
I have integration a scenario of testing  webdriverio V6(native) and Protractor(web) together.
Json file is not creating when launching Protractor browser via wdio
But earlier it was working.
Changed following packages chromdriver 81 and  "@wdio/cucumber-framework": "^6.1.1"
I am able to create json if I don't launch protractor browser

**If it's about a specific piece of code, try and include some of it to support your question.**
I was launching protractor via webdriverio config, working as expected.
const ptorRunner = new ProtractorRunner(ptorConfig);
  const browser = ptorRunner.createBrowser();

 

**Environment (please complete the following information):**
  "wdio-chromedriver-service": "^6.0.2",
    "wdio-cucumberjs-json-reporter": "^1.3.0"
 "@wdio/cucumber-framework": "^6.1.1",
 "webdriverio": "^6.0.15"

**Additional context**

**Comment by krishna01012002** [comment]
Sorry my issue is fixed

**Comment by wswebcreation** [comment]
Always nice issues that are closed by themselves 😉
