### ISSUE TITLE
How to know if a scenario is passed after retried if "specFileRetries" is applied WDIO in config file

### ISSUE THREAD

**Issue by pradeepnyk** [wswebcreation/wdio-cucumberjs-json-reporter#30]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)
I have wdio config file with `specFileRetries: 1`, and it retries if the test execution fails for any spec file, hence my spec reporter says pass:1, fail:0, retry:1. This means, the execution is passed only after 1 retry. I want to have the similar report on my cucumber report json file. But actual behaviour is: the report shows 1 TC as failed, 1TC passed, because it has executed 2 times, and failed once out of this.
Is there any other config to apply to achive ?

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - **Node.js version:** 12.15.0
 - **NPM version:** 6.14.2
 - **webdriver.io version:** 5.18.6
 - **@wdio/cucumber-framework version:** 5.18.6
 - **wdio-cucumberjs-json-reporter version:** 1.0.7

**Additional context**

**Comment by wswebcreation** [comment]
Hi @pradeepnyk 

No, there is (currently) no option to do that. This module will just create a JSON file for each test execution. As far as I can see, hard to find official reporting docs of Cucumber, there is also no report out there that supports retries
