### ISSUE TITLE
JSON result is not generated when BROWSER_TIMEOUT in selenium grid

### ISSUE THREAD

**Issue by icelandld815** [wswebcreation/wdio-cucumberjs-json-reporter#33]
**Environment (please complete the following information):**
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **webdriver.io version:** 5.22.4
 - **@wdio/cucumber-framework version:** 5.20.0
 - **wdio-cucumberjs-json-reporter version:** 1.2.1

**Config of webdriver.io and the reporter**

    reporters: ['spec',
        ['cucumberjs-json', {
            jsonFolder: path.resolve(path.join(process.cwd(), '/outputs/json/')),
        }]
    ],

**Describe the bug**
The report json file is not generated when an 'BROWSER_TIMEOUT' error encounter in selenium gird. It seems the 'onRunnerEnd' method is not executed due to this error.

**To Reproduce**
write some cucumber ui testing step
hard code 'browser.closeWindow();' in one of the step to simulate the browser_timout error.
Execute the testing against selenium grid !!!

**Comment by wswebcreation** [comment]
@icelandld815 

WebdriverIO provides all kinds of methods a reporter could use, this report is just using those methods and if they are not being called from WebdriverIO, then this issue should be logged in the WebdriverIO repo instead of here
