### ISSUE TITLE
Does the .json reporter generate steps with 'pending' status ?

### ISSUE THREAD

**Issue by IlionaIlly** [wswebcreation/wdio-cucumberjs-json-reporter#34]
**Describe your question with as much detail as possible**
I am trying to work with tagged hooks as explained here https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#tagged-hooks and generate the status `pending` in the reporter for certain step definitions. 

**Feature file**
```
@Manual
    Scenario: Open Browser
        Given I open the url "https://www.google.com"
        Given the title is "Google"

```
**Hooks.js file**
import { Before } from 'cucumber';

```
Before({ tags: '@Manual' }, () => {
    return 'pending';
});
```
**Expected Result**
After execution the first step is marked as `pending` and the rest is marked as `skipped`.

**Actual Result**
After execution all the steps with the tag pending are marked as `skipped`. 

Note : I am trying to reproduce the report with the tag `@pending` here https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/features/f92886a9-c154-4c33-8bb5-3b61d7339dc8-undefined-pending-passed-scenarios-specified-v3.html

**Environment (please complete the following information):**
 - **Node.js version:** [10.16.3]
 - **NPM version:** [6.13]
 - **webdriver.io version:** [6.0.16]
 - **@wdio/cucumber-framework version:** [6.0.16]
 - **wdio-cucumberjs-json-reporter version:** [1.3.0]

**Additional context**

**Comment by wswebcreation** [comment]
Hi @IlionaIlly 

Currently WebdriverIO doesn't expose `pending` as an officials status that can be picked up by the reporter class of WebdriverIO. I need to check if I can retrieve it somewhere with a workaround and will put it on my todo list

**Comment by wswebcreation** [comment]
Also created a feature request for WebdriverIO https://github.com/webdriverio/webdriverio/issues/5359
