### ISSUE TITLE
wdio-cucumberjs-json-reporter doesn't report variables in dataTables from Scenarios Outline Examples

### ISSUE THREAD

**Issue by JuanRodriguezAbarca** [wswebcreation/wdio-cucumberjs-json-reporter#36]
There is an issue which persists along wdio versions which is parsing variable values from Examples in Scenario Outline to the Json Reporter in data tables

 See the report:
![image](https://user-images.githubusercontent.com/11064158/82906134-15887880-9f65-11ea-8dd5-7dd2684e9128.png)
And the feature:
![image](https://user-images.githubusercontent.com/11064158/82905664-6f3c7300-9f64-11ea-9a23-3e36736ceb41.png)
![image](https://user-images.githubusercontent.com/11064158/82906451-90519380-9f65-11ea-8c4b-0dd233cd2a0b.png)

The execution is ok, the problem happens when parsing the variable. See the json report block:
```
`{
	"arguments": [
		{
			"rows": [
				{
					"cells": [
						"name",
						"description",
						"accountPlan",
						"API",
						"environment",
						"apps"
					],
					"locations": [
						{
							"line": 13,
							"column": 21
						},
						{
							"line": 13,
							"column": 30
						},
						{
							"line": 13,
							"column": 46
						},
						{
							"line": 13,
							"column": 62
						},
						{
							"line": 13,
							"column": 70
						},
						{
							"line": 13,
							"column": 86
						}
					]
				},
				{
					"cells": [
						"<name>",
						"<description>",
						"<accountPlan>",
						"<API>",
						"<environment>",
						""
					],
					"locations": [
						{
							"line": 14,
							"column": 21
						},
						{
							"line": 14,
							"column": 30
						},
						{
							"line": 14,
							"column": 46
						},
						{
							"line": 14,
							"column": 62
						},
						{
							"line": 14,
							"column": 70
						},
						{
							"line": 14,
							"column": 91
						}
					]
				}
			]
		}
	],
	"keyword": "Given",
	"name": "existing organization with following data",
	"result": {
		"status": "passed",
		"duration": 7000000
	},
	"line": 12,
	"match": {
		"location": "can not be determined with webdriver.io"
	}
}`

```
Which is taken in the html as html nodes because the '<>; symbols

My npm dependencies:
"devDependencies": {
    "@babel/cli": "7.8.4",
    "@babel/core": "7.9.0",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.7.0",
    "@wdio/cucumber-framework": "6.1.13",
    "@wdio/local-runner": "5.23.0",
    "@wdio/spec-reporter": "5.23.0",
    "@wdio/sync": "5.23.0",
    "chromedriver": "^83.0.0",
    "expect": "24.3.0",
    "expect-webdriverio": "0.2.0",
    "fs-extra": "^9.0.0",
    "geckodriver": "^1.19.1",
    "multiple-cucumber-html-reporter": "^1.16.2",
    "wdio-chromedriver-service": "5.0.2",
    "wdio-cucumberjs-json-reporter": "^2.0.0",
    "wdio-geckodriver-service": "^1.0.3",
    "winston": "^3.2.1",
    "yargs": "^15.3.1"

As an example, a dummy scenario outline which is feeds a step data table

```
Scenario Outline: Google outline <time>
    Given I open Google for the time
        |time|weather|
        |<time>|<wheather>|

    Examples:
      | time      |wheather|
      | first       |  cold      |
      | second |  warm     |
```

**Comment by wswebcreation** [comment]
@JuanRodriguezAbarca 

Thanks for the clear issue and sorry for ping-poinging you from project to project, but this is not an issue in this module. I've reopened your initial issue because it's or in WebdriverIO, or Cucumber
