### ISSUE TITLE
Error thrown when provided config with scenarioLevelReporter: true

### ISSUE THREAD

**Issue by vmwhereqa** [wswebcreation/wdio-cucumberjs-json-reporter#38]
**Environment (please complete the following information):**
 - **Node.js version:** [12.16.3]
 - Yarn - 1.22.4
 - **webdriver.io version:** [6.1.22]
 - **@wdio/cucumber-framework version:** [6.1.22]
 - **wdio-cucumberjs-json-reporter version:** [2.0.2]

**Config of webdriver.io and the reporter**
 cucumberOpts: {
    // <string[]> (file/dir) require files before executing features
    require: [
      "./src/step_definitions/**.steps.js",
      "./src/support/hooks/**.hooks.js",
    ],
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
    requireModule: ["@babel/register"],
    // <boolean> invoke formatters without executing steps
    dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
    format: ["pretty"],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <boolean> fail if there are any undefined or pending steps
    strict: false,
    // <string> (expression) only execute the features or scenarios with tags matching the expression
    tagExpression: "",
    // <number> timeout for step definitions
    timeout: 60000,
    // <boolean> Enable this config to treat undefined definitions as warnings.
    ignoreUndefinedDefinitions: false,
    // <boolean> Add cucumber tags to feature or scenario name.
    tagsInTitle: false,
    scenarioLevelReporter: true
  },

**Describe the bug**
When added with cucumber option  `scenarioLevelReporter: true`, then the following error is thrown

**To Reproduce**
Just add `scenarioLevelReporter: true` and run the test

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Snapshots**
If applicable, add snapshots to help explain your problem.

**Additional context**

**Comment by DanielLopez-nbcuni** [comment]
I'm running into the same issue.
