### ISSUE TITLE
escaping of chars in steps in the produced JSON report

### ISSUE THREAD

**Issue by bitcoder** [wswebcreation/wdio-cucumberjs-json-reporter#4]
**Environment (please complete the following information):**
 - **Node.js version:** v12.6.0
 - **NPM version:** 6.9.0
 - **webdriver.io version:** 5.11.0
 - **@wdio/cucumber-framework version:** 5.11.0
 - **wdio-cucumberjs-json-reporter version:** 1.0.5

**Config of webdriver.io and the reporter**

```js
const { TimelineService } = require('wdio-timeline-reporter/timeline-service');

exports.config = {
    runner: 'local',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    specs: ['./test/e2e/features/*.feature'],
    maxInstances: 1,
    capabilities: [
        {
            maxInstances: 1,
            browserName: 'chrome',
            'zal:recordVideo': true,
            'zal:name': 'Demo Integration Tests',
            'zal:build': 'WebDriverIO',
        },
    ],
    logLevel: 'trace',
    bail: 0,
    baseUrl: 'http://automationpractice.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    framework: 'cucumber',
    reporters: [
        'dot',
        'spec',
	'cucumberjs-json',
        [
            'allure',
            {
                outputDir: './test-report/allure-result/',
                disableWebdriverStepsReporting: false,
                disableWebdriverScreenshotsReporting: false,
            },
        ],
        ['timeline', { outputDir: './test-report/timeline' }],
    ],
    cucumberOpts: {
        require: ['./test/e2e/steps/*.steps.js'],
        backtrace: false,
        compiler: [],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        profile: [],
        strict: false,
        tags: [],
        timeout: 60000,
        ignoreUndefinedDefinitions: false,
    },
    services: [
        [TimelineService],
        // Uncomment to run tests with Selenium Standalone, if you have JDK installed.
         ['selenium-standalone'],
    ],
    before() {
        browser.setWindowSize(1920, 1080);
    },
    beforeSession: function beforeTest() {
        require('@babel/register');
    },
};
```

**update to markdown**

**Describe the bug**

**To Reproduce**

- clone the repo: https://github.com/WarleyGabriel/demo-webdriverio-cucumber
- configure wdio.conf.js as mentioned above
- run tests using: yarn run e2e:tests

**Expected behavior**
the produced json reports should have the steps properly escaped as json strings; however it seems that they're being HTML escaped.

**Snapshots**
the following screenshots show the original Scenario at the top, having the ' character. when it is run, however the produced json report contains the steps incorrectly formatted. the screenshot is taken on [Xray](https://marketplace.atlassian.com/apps/1211769/xray-test-management-for-jira?hosting=server&tab=overview) after importing the results.

![image](https://user-images.githubusercontent.com/553801/61805097-14f6f100-ae2d-11e9-9ef0-c8b73e83bca7.png)

**Additional context**

[sending-message-to-customer-service.1563978979779.json.txt](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/files/3427467/sending-message-to-customer-service.1563978979779.json.txt)

**Comment by wswebcreation** [comment]
Hi @bitcoder 

Thanks for the issue, the issue is in here:

- https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L224
- https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L226
- https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L256
- https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L257
- https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/master/lib/reporter.js#L293

They need to be changed. I implemented the escaping of HTML because in the past I had users having problem with this. 

If you want you can create a PR for it, otherwise I'll pick it up later

**Comment by bitcoder** [comment]
Hi @wswebcreation , you're welcome.
I would create a PR but unfortunately I'm no node expert :(
However I think something like this could work out: https://stackoverflow.com/questions/4253367/how-to-escape-a-json-string-containing-newline-characters-using-javascript

**Comment by wswebcreation** [comment]
I can help you with it if you want, we can chat privately on Gitter for example and ai can guide you through the process. Then it will be you first NodeJS PR 😉

**Comment by bitcoder** [comment]
will try it then :) let's see how it goes. I'll proceed the talk with you on gitter
