### ISSUE TITLE
Line value in JSON is missing or an empty string

### ISSUE THREAD

**Issue by WilliamFClarke** [wswebcreation/wdio-cucumberjs-json-reporter#50]
- **Node.js version**: 14.16.1 
 - **NPM version**: 6.14.12
 - **webdriver.io version**: 7.5.1
 - **@wdio/cucumber-framework version**: 7.0.7
 - **wdio-cucumberjs-json-reporter version**: 2.0.3

**Config of webdriver.io and the reporter**
Example Project Conf file: https://github.com/WilliamFClarke/webdriverio-cucumber-boilerplate/blob/master/wdio.conf.js

**Describe the bug**
In the report JSON the "line" value is sometimes returned as an empty string ("") when it must be an integer and the line value is also missing at the element level. 
This goes against the schema listed here: (https://github.com/cucumber/cucumber-json-schema/blob/main/schema.json)
In my case this is causing a validation error when attempting to upload test results to [Zephyr Scale](https://smartbear.com/test-management/zephyr-scale/) as they have strict enforcement of the JSON.

Example incorrect JSON:

`[{"keyword":"Feature","type":"feature","description":"","line":null,"name":"Homepage","uri":"Can not be determined","tags":[],"elements":[{"keyword":"Scenario","type":"scenario","description":"","name":"As a user, I can view the homepage","tags":[],"id":"homepage;as-a-user,-i-can-view-the-homepage","steps":[{"arguments":[],"keyword":"Before","name":"","result":{"status":"passed","duration":1000000},"line":18,"match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Given","name":"I am on the home page","result":{"status":"passed","duration":2582000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"When","name":"I check the title","result":{"status":"passed","duration":58000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Then","name":"peform a fullscreen image check with tag homePage","result":{"status":"passed","duration":2737000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"After","name":"","result":{"status":"passed","duration":1000000},"line":22,"match":{"location":"can not be determined with webdriver.io"}}]}],"id":"homepage","metadata":{"browser":{"name":"Chrome Headless","version":"90.0.4430.85"},"device":"Device name not known","platform":{"name":"win32","version":"Version not known"}}},{"keyword":"Feature","type":"feature","description":"","line":null,"name":"Homepage","uri":"Can not be determined","tags":[],"elements":[{"keyword":"Scenario","type":"scenario","description":"","name":"As a user, I can view the homepage","tags":[],"id":"homepage;as-a-user,-i-can-view-the-homepage","steps":[{"arguments":[],"keyword":"Before","name":"","result":{"status":"passed","duration":1000000},"line":18,"match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Given","name":"I am on the home page","result":{"status":"passed","duration":2567000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"When","name":"I check the title","result":{"status":"passed","duration":19000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Then","name":"peform a fullscreen image check with tag homePage","result":{"status":"passed","duration":2761000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"After","name":"","result":{"status":"passed","duration":0},"line":22,"match":{"location":"can not be determined with webdriver.io"}}]}],"id":"homepage","metadata":{"browser":{"name":"Chrome Headless","version":"90.0.4430.85"},"device":"Device name not known","platform":{"name":"win32","version":"Version not known"}}},{"keyword":"Feature","type":"feature","description":"","line":null,"name":"Homepage","uri":"Can not be determined","tags":[],"elements":[{"keyword":"Scenario","type":"scenario","description":"","name":"As a user, I can view the homepage","tags":[],"id":"homepage;as-a-user,-i-can-view-the-homepage","steps":[{"arguments":[],"keyword":"Before","name":"","result":{"status":"passed","duration":1000000},"line":18,"match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Given","name":"I am on the home page","result":{"status":"passed","duration":4895000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"When","name":"I check the title","result":{"status":"passed","duration":21000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"Then","name":"peform a fullscreen image check with tag homePage","result":{"status":"passed","duration":2762000000},"line":"","match":{"location":"can not be determined with webdriver.io"}},{"arguments":[],"keyword":"After","name":"","result":{"status":"passed","duration":0},"line":22,"match":{"location":"can not be determined with webdriver.io"}}]}],"id":"homepage","metadata":{"browser":{"name":"Chrome Headless","version":"90.0.4430.85"},"device":"Device name not known","platform":{"name":"win32","version":"Version not known"}}}]`

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Example Project: https://github.com/WilliamFClarke/webdriverio-cucumber-boilerplate 
2. Run the example repo with `npm test` 
3. Open the json file in the folder  `./cucumberResults`

**Expected behavior**
The JSON file should conform to these rules: https://github.com/cucumber/cucumber-json-schema/blob/main/schema.json

**Additional context**
While looking if anyone else has this issue I noticed its been mentioned within another issue here: https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/issues/47#issuecomment-785200046
while this fix suggested resolves the empty string in the line value it doesn't resolve the missing line value at the element level of the JSON.

**Comment by wswebcreation** [comment]
Thanks for the detailed issue @WilliamFClarke 

I need to look into this, but if you have some time then a PR would be welcome 😉

**Comment by wswebcreation** [comment]
Released https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/releases/tag/v2.0.4, thanks!
