### ISSUE TITLE
How can we attach multiple screenshots to a cucumber step ?

### ISSUE THREAD

**Issue by krarpitgupta** [wswebcreation/wdio-cucumberjs-json-reporter#52]
Hi Team, I am able to attach a single screenshot to a cucumber step but my requirement is such that where I need to attach multiple screenshots to a cucumber steps, May I know how can we do it ?

for e.g. 

cucumberJson.attach(browser.takeScreenshot(), 'image/png'); // It's attaching single screenshot

But when I am calling same code multiple times within a cucumber step then it's just attaching the last screenshot

**Comment by wswebcreation** [comment]
Hi @krarpitgupta 

Can you provide an example? I've ran this and it works as expected

```js
Given('I have {int} cukes in my belly', (cukeCount) => {
  // Attach a screenshot in a before hook
  cucumberJson.attach(browser.takeScreenshot(), 'image/png');
  // Attach a screenshot in a before hook
  cucumberJson.attach(browser.takeScreenshot(), 'image/png');
  // Attach a screenshot in a before hook
  cucumberJson.attach(browser.takeScreenshot(), 'image/png');
  return true
})
```

![screenshot-cucumberjs](https://user-images.githubusercontent.com/11979740/116662765-7b138f00-a996-11eb-887e-959d1ad9fbd6.png)

**Comment by krarpitgupta** [comment]
Hi @wswebcreation I am using cucumber-html-reporter, here is my code snipppet

`for(j = 0; j < companyInfo.length; j++){
        
        companyId = companyInfo[j].company_id;
        companyName = companyInfo[j].company_name;
        companyEnable = companyInfo[j].include_header;
        disableMenuFlag = appComponents.checkDisableMenuFor(disableCompanyObj, companyId, defaultEndYear);

        if (companyEnable == 'T'){

            if(!disableMenuFlag){

                screenSearchStringURL = (screenConfig[screenDesc].searchString)
                .replace('$companyId$', companyId)
                .replace('$currency$', defaultCurrency)
                .replace('$endYear$', defaultEndYear);

                browser.url(screenSearchStringURL);
                
                lib.waitForAngularToLoad();
                lib.compareText(lib.getText('text', 'CompanyHeading'), companyName, true);
                lib.compareText(loginPage.getScreenTitle(), screenTitle, true);
                
                if(lib.isDisplayed('DataNotAvailableSection')){

                    count++;
                    actions.clickElement('click', 'selector', 'DataNotAvailableSection', 0);
                    allureReporter.addStep(`${companyName}=>${screenTitle}=>${browser.getUrl()}`);
                    cucumberJson.attach(`${companyName}=>${screenTitle}=>${browser.getUrl()}`);
                    brokenScreens.push(`${companyName}=>${screenTitle}=>${browser.getUrl()}`);
                    fileName = `/${screenTitle.toLowerCase()}_${companyName.toLowerCase().replace('"','')}_${defaultCurrency.toLowerCase()}_${defaultEndYear}.png`;
                    lib.captureBrowserScreenshot(path.join(dirPath, fileName));
                    cucumberJson.attach(browser.takeScreenshot(), 'image/png');
                    
                }

            }
            else {
                disableMenu.push(`${companyId}`);
            }
        }
    }
    `

Here is the sample report :

![image](https://user-images.githubusercontent.com/37265099/116663678-13207100-a9b5-11eb-8f50-5cee4b145185.png)

**Comment by wswebcreation** [comment]
Can you check the json output? Because it looks like a limitation in the reporter that you are using

**Comment by krarpitgupta** [comment]
@wswebcreation Yes seems like limitation with cucumber-html-reporter

**Comment by krarpitgupta** [comment]
@wswebcreation I check the generated json and I can see multiple entries for snapshot data, but in the generated html only 1

**Comment by wswebcreation** [comment]
@krarpitgupta 

This is not an issue with this reporter, as you mentioned it generates multiple images in the JSON. This is an issue with the `cucumber-html-reporter`-module and I don't maintain that one. So please file an issue there
