### ISSUE TITLE
Screenshots on failure in WDIO cucumber boilerplate

### ISSUE THREAD

**Issue by senovsky** [wswebcreation/wdio-cucumberjs-json-reporter#9]
**Pre-check**
- [✓] I'm aware that I can [edit the docs](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter) and submit a pull request

**Describe the improvement**
I'd like to report
- Missing documentation

**Description of the improvement / report**
Hi, could you please elaborate on taking screenshots on failure, in [WDIO cucumber boilerplate](https://github.com/webdriverio/cucumber-boilerplate)? I was able to figure out how to use the afterStep hook in wdio.conf.js:

```
afterStep: function (uri, feature, scenario, step, result) {
    if (result.status === 'failed') {
        cucumberJson.attach(browser.takeScreenshot(), 'image/png');
    }
},
```

However, I'm struggling with importing your module. `import cucumberJson from 'wdio-cucumberjs-json-reporter';` gives me a compilation error
```
        import cucumberJson from 'wdio-cucumberjs-json-reporter';
               ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```

Rewriting it into ES5 syntax `const cucumberJson = require('wdio-cucumberjs-json-reporter');` gives me a runtime error
```
[0-0] 2019-08-13T16:16:55.049Z ERROR @wdio/sync: TypeError: cucumberJson.attach is not a function
    at Object.afterStep (C:\Users\smt\e2e\wdio.conf.js:267:26)
    at execHook (C:\Users\smt\e2e\node_modules\@wdio\sync\build\executeHooksWithArgs.js:30:23)
```

**Comment by robsonpolicarpo** [comment]
Hi @senovsky !

I can put the image in report this way:

I'm using ES6

const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
cucumberJson.attach(browser.takeScreenshot(), 'image/png');

**Comment by senovsky** [comment]
Thanks, that's what I was looking for :-)
